### ISSUE TITLE
Mime validation checks given type, not file read type

### ISSUE THREAD

**Issue by rubicon9** [codingedward/flask-sieve#13]
Hey @codingedward , another one here. I fixed this myself by using Python Magic. However, this library is a little heavyweight so I'm not sure if there's a lighter weight way of doing this? Let me know your thoughts, I can open a PR for this one too :)

https://github.com/codingedward/flask-sieve/blob/d47bbed00ace71a9c4609bec8a493e416f25240c/flask_sieve/rules_processor.py#L374-L378

As per docs (same with Laravel's Validator too), mime checking should be by reading the header of the actual file itself, not by the 'given' mime type from the browser. This is a great way of actually checking the file type in the instance that the client is deliberately or accidentally misreporting the mime.

Currently it just reads the input file params from the client.

Expected behaviour:
Should read the actual file and ascertain the mime.

**Comment by codingedward** [comment]
Hello @rubicon9, 

Thanks for raising the issue 🎉 . I agree it is definitely a problem (especially security-wise) to be using the provided mime type from the client and we ought to fix it.

I have also looked through the Python Magic library you mentioned and it looks like a viable and reliable way to get the correct mime types in Python. Personally I wouldn't worry about it being heavyweight so long as it is reliable (which it seems to be).

If you are able to, feel free to put up a PR. I'd appreciate it 👍 .

**Comment by codingedward** [comment]
Decided to work on this due to inactivity. After having tried using libmagic locally, I also settled for a more lightweight package here: https://github.com/h2non/filetype.py.

The reasoning is I realized one has to install `libmagic` in addition to installing `python-magic` and that would break the usage of this package and not be backwards compatible. I like the fact that `filetype` is lightweight and works out of the box and so I think that's the more appropriate library.

**Comment by rubicon9** [comment]
> Decided to work on this. After having tried using libmagic locally, I also settled for a more lightweight package here: https://github.com/h2non/filetype.py.
> 
> The reasoning is I realized one has to install `libmagic` in addition to installing `python-magic` and that would break the usage of this package and not be backwards compatible. I like the fact that `filetype` is lightweight and works out of the box and so I think that's the more appropriate library.

Thanks Edward! It's been on my todo list for the last couple of weeks - just been busy. Sorry about that.

Library looks great, and lightweight. So win-win 👍

**Comment by codingedward** [comment]
Closed by: https://github.com/codingedward/flask-sieve/pull/14

Thanks again for raising the issue.
