### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by Khalid-noor** [codingedward/flask-sieve#19]
Hello

I think I found a bug with `required_without` and `required_without_all` when I used it with parameter type.

example:

```
def rules(self):
        return {
            'id': ['required_without:name', integer],
            'name': ['required_without:id', 'string']
        }
```

and When the request json only has ID
```
{
   "id": 123
}
```

the error response is:
```
{
  "errors": {
    "user_id": [
      "The name must be an string."
    ]
  },
  "message": "Validation error",
  "success": false
}
```

Can You please check this issue?

**Comment by codingedward** [comment]
Hi @Khalid-noor, thanks for raising this. This is definitely a bug and I'll look into working on a fix for it.
