### ISSUE TITLE
JSON Data Validation Failed

### ISSUE THREAD

**Issue by RajbirSehrawat** [codingedward/flask-sieve#21]
I am sending this data in request

{
  "firstName": "string",
  "lastName": "string",
  'email':""
}

**Error i am getting :-** Failed to decode JSON object: Expecting property name enclosed in double quotes: line 4 column 3 (char 53)

**my validation rule is**

 rules = {
        'email': ['present','required', 'email'],
    }
    validator = Validator(rules=rules, request=request)

    if not validator.passes():
        return jsonify(validator.messages()), 400

**Comment by codingedward** [comment]
Hi @RajbirSehrawat,

This is, unfortunately, another weird part of the JSON specification. The JSON standard expects double quotes on property names. Therefore:

```json
{
"firstName": "string",
"lastName": "string",
'email':""
}```

is not valid JSON. 

StackOverflow related question: https://stackoverflow.com/questions/36038454/parsing-string-as-json-with-single-quotes/36038497#:~:text=7%20Answers&text=The%20JSON%20standard%20requires%20double,end%20up%20with%20valid%20JSON.

Again, if you were to use a JSON parsing library on the client side, this is not something you'll have to worry about.

**Comment by RajbirSehrawat** [comment]
Its working fine. Thanks
