### ISSUE TITLE
Required and Present rule not working with Trailing Comma

### ISSUE THREAD

**Issue by RajbirSehrawat** [codingedward/flask-sieve#22]
Validation Rule stop working if left comma at the end of input request

I am sending this data in request - 

**This is working**

{
  "firstName": "string",
  "lastName": "string"
}

**Below is not working**

{
  "firstName": "string",
  "lastName": "string",
}

I miss to remove comma from last input in request data :

**Errors :-** Failed to decode JSON object: Expecting property name enclosed in double quotes: line 4 column 3 (char 53)

**my validation rule is**

 rules = {
        'email': ['present','required', 'email'],
    }
    validator = Validator(rules=rules, request=request)

    if not validator.passes():
        return jsonify(validator.messages()), 400

**Comment by codingedward** [comment]
Hi @RajbirSehrawat, thanks for raising this and sorry for the late reply! 

You'd be surprised (perhaps as much as I am) that trailing commas are actually not part of JSON's specification: https://stackoverflow.com/questions/201782/can-you-use-a-trailing-comma-in-a-json-object#:~:text=Unfortunately%20the%20JSON%20specification%20does,s.

If you make sure to use a JSON parsing library when making requests, this will be caught earlier before hitting the server.

**Comment by RajbirSehrawat** [comment]
Thanks for the reply.
