### ISSUE TITLE
Boolean is showing required if pass value false or 0

### ISSUE THREAD

**Issue by RajbirSehrawat** [codingedward/flask-sieve#26]
Hi Team,

Boolean is showing validation fail if I pass the value false or zero. 

Please try to resolve these bug ASAP or please also make me the contributor. so that i can fix these too.

My Request Data :

{
  "UUID": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "adminLeadRecruiter": false,
  "adminAsDcm": false,
  "leadRecruiters": [
    "abc@gmail.com",
    "xyz@abc.com"
  ],
  "recruiters": [
    "abc@gmail.com",
    "xyz@abc.com"
  ],
  "dcm": "abc@gmail.com"
}

**Response :-**

"errors": {
    "adminAsDcm": [
      "The adminAsDcm field is required."
    ],
    "adminLeadRecruiter": [
      "The adminLeadRecruiter field is required."
    ]
  },

**Comment by codingedward** [comment]
Hi @RajbirSehrawat, sorry I have been a bit attached at work.

Contributions are most welcome and you can still work on this if you'd want by forking the project, working on it on your local machine, and then raising a Pull Request.

Let me know if there's any other way I can help.
