### ISSUE TITLE
Equivalent of "sometimes"

### ISSUE THREAD

**Issue by calina-c** [codingedward/flask-sieve#27]
Is there an equivalent of "sometimes" from Laravel validation? i.e. only validate the value if present and non-empty, otherwise skip the validation.

**Comment by codingedward** [comment]
Hi @calina-c, unfortunately for now we don't have an equivalent rule for "sometimes" as at the time of creation Laravel did not include it. 

Definitely something we should look into adding, and I'd appreciate contributions if possible! I could still work on it later though if you'd prefer.

For now, I think the closest to that rule would be to use `"nullable"`, which will skip validation if the value is not provided. I think it still makes that check if the value is provided but empty though.

**Comment by calina-c** [comment]
@codingedward I can't promise right now, but I might be available in the following days to help with that.

**Comment by codingedward** [comment]
Sounds good, thank you!
