### ISSUE TITLE
Max Rule Not Working for Numeric String

### ISSUE THREAD

**Issue by rajbirikon** [codingedward/flask-sieve#36]
My rule is this

rules = {
                'card_number': ['bail', 'required', 'string', 'max:20'],
                'card_expiry_date': ['bail', 'required','string', 'max:8'],
                'card_cvv': ['bail', 'required', 'string', 'max:8']
            }

I am passing the values 

card_number = "876545666"
card_expiry_Date="0234"
card_cvv="123"

but this show error max value must be 20. 

How can we validate that the string characters max:20 for value "8777745434"

**Comment by codingedward** [comment]
Hello, sorry for the late response. That is definitely a bug. Looking to see if I can get it resolved

**Comment by codingedward** [comment]
This has now been fixed on #37 🎉
