### ISSUE TITLE
Nullable or Integer

### ISSUE THREAD

**Issue by schumskie** [codingedward/flask-sieve#7]
If I provide these two rules to a field, I'm expecting to be able to send value which could be None **or** some Integer. But currently if I don't send anything (sending null in this case), validation fails, saying that value must be an int. Shouldn't it allow null value also if I specified it like that?

**Comment by codingedward** [comment]
Hi @schumskie, thanks for raising the issue. Let me look through it and I will raise a fix.

**Comment by schumskie** [comment]
Okey thank you very much :)

сре, 1. апр 2020. у 00:34 Edward Njoroge <notifications@github.com> је
написао/ла:

**Comment by codingedward** [comment]
This has now been fixed here: https://github.com/codingedward/flask-sieve/pull/8 🎉  thanks for your patience, was really tied at work.
