### ISSUE TITLE
Dimensions check does not work

### ISSUE THREAD

**Issue by rubicon9** [codingedward/flask-sieve#9]
https://github.com/codingedward/flask-sieve/blob/6d419dcc1d97868b1054abf4c81972e960cceba7/flask_sieve/rules_processor.py#L197-L199

As per snippet:
1) The object passed for validation as `value` is a FileObject from a form submission; `filename` does not reference the file path.
Suggest: `image = Image.open(value)`

2) Closing the image causes problems for downstream stream processing.
Instead suggest removing `image.close()` and replacing with `value.seek(0)`

Tests will also need to be updated to reflect these changes.

**Comment by rubicon9** [comment]
Fixed in PR: https://github.com/codingedward/flask-sieve/pull/10

**Comment by codingedward** [comment]
Hello, sorry for the late reply, and thanks for raising the issue! 🎉

**Comment by codingedward** [comment]
Closed by #10
